"""
services/export_store.py
─────────────────────────
Storage for files the assistant generates — Word reports, Excel exports.

Until now these were built, returned over the API, and discarded, so a person
was told their export succeeded and received nothing. This is where they live
instead.

Ownership is encoded in the object key rather than in a database table:

    exports/{user_id}/{export_id}/{filename}

which means a different user resolving the same export id looks under a
different prefix and simply finds nothing. No table to join, nothing to keep in
step, and no way to forget the ownership check — it is the path.

Filenames come from the model, so they are untrusted. Only the basename is
kept, so nothing in a generated name can point the key outside its own prefix.
"""

from __future__ import annotations

import io
import uuid
from datetime import datetime, timezone
from pathlib import PurePosixPath

import structlog
from minio.error import S3Error

from config.settings import get_settings
from services.minio_service import _get_client, ensure_bucket_exists

logger = structlog.get_logger(__name__)
settings = get_settings()

PREFIX = "exports"
FALLBACK_FILENAME = "export.bin"


class ExportNotFound(Exception):
    """No such export for this user."""


def _bucket() -> str:
    return settings.minio_bucket_documents


def ensure_bucket() -> None:
    ensure_bucket_exists(_bucket())


def _safe_filename(filename: str) -> str:
    """
    Reduce a model-supplied filename to a harmless basename.

    Traversal segments and directories are stripped rather than rejected: the
    file has already been generated by this point, and losing it over a stray
    slash in a title would be a worse outcome than a tidied name.
    """
    name = PurePosixPath((filename or "").replace("\\", "/")).name
    name = name.strip().strip(".")
    return name or FALLBACK_FILENAME


def build_object_key(user_id: str, export_id: str, filename: str) -> str:
    """Where one user's export lives. Ownership is the prefix."""
    if not user_id:
        raise ValueError("user_id is required — it is the access control")
    if not export_id:
        raise ValueError("export_id is required")
    return f"{PREFIX}/{user_id}/{export_id}/{_safe_filename(filename)}"


def parse_object_key(object_key: str) -> dict:
    """Split a key back into owner, export and filename."""
    parts = object_key.split("/")
    if len(parts) < 4 or parts[0] != PREFIX:
        raise ValueError(f"not an export key: {object_key!r}")
    return {"user_id": parts[1], "export_id": parts[2], "filename": "/".join(parts[3:])}


def save_export(
    user_id: str,
    filename: str,
    data: bytes,
    mime_type: str = "application/octet-stream",
) -> str:
    """
    Store a generated file and return its export id.

    The id is what appears in the download link; it is not guessable, and on its
    own it is not enough — the download also checks the owner.
    """
    ensure_bucket()
    export_id = str(uuid.uuid4())
    key = build_object_key(user_id, export_id, filename)

    _get_client().put_object(
        bucket_name=_bucket(),
        object_name=key,
        data=io.BytesIO(data),
        length=len(data),
        content_type=mime_type,
        metadata={
            # Header-safe: MinIO sends these as HTTP metadata, so a non-ASCII
            # filename would break the response rather than the upload.
            "x-amz-meta-filename": _safe_filename(filename).encode(
                "ascii", "replace"
            ).decode("ascii"),
            "x-amz-meta-created": datetime.now(timezone.utc).isoformat(),
        },
    )
    logger.info(
        "export_store.saved",
        export_id=export_id,
        filename=filename,
        bytes=len(data),
    )
    return export_id


def load_export(user_id: str, export_id: str) -> dict:
    """
    Fetch one of this user's exports.

    Raises ExportNotFound when the export does not exist *or* belongs to
    somebody else — the two are indistinguishable by design, so an export id is
    not a way to discover that another user has a file.
    """
    if not user_id or not export_id:
        raise ExportNotFound("missing owner or export id")

    client = _get_client()
    bucket = _bucket()
    prefix = f"{PREFIX}/{user_id}/{export_id}/"

    try:
        objects = list(client.list_objects(bucket, prefix=prefix, recursive=True))
    except S3Error as e:
        logger.error("export_store.list_failed", prefix=prefix, error=str(e))
        raise ExportNotFound(f"could not read export {export_id}") from e

    if not objects:
        raise ExportNotFound(f"no export {export_id} for this user")

    key = objects[0].object_name
    try:
        response = client.get_object(bucket_name=bucket, object_name=key)
        data = response.read()
        response.close()
        response.release_conn()
    except S3Error as e:
        logger.error("export_store.get_failed", key=key, error=str(e))
        raise ExportNotFound(f"could not read export {export_id}") from e

    stat = client.stat_object(bucket_name=bucket, object_name=key)
    return {
        "data": data,
        "filename": parse_object_key(key)["filename"],
        "mime_type": stat.content_type or "application/octet-stream",
        "size": len(data),
    }
