"""
tools/export_tool.py
─────────────────────
Document export tool for Word (.docx) and Excel (.xlsx) generation.

The LLM can request exports by calling these tools:
  - export_to_word: Generate a .docx report from retrieved content + answer
  - export_to_excel: Generate an .xlsx file from tabular data in retrieved chunks
"""

from __future__ import annotations

import io
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import structlog
from docx import Document as DocxDocument
from docx.shared import Pt, RGBColor
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

logger = structlog.get_logger(__name__)

# ── Tool Definitions ──────────────────────────────────────────────────────────

EXPORT_WORD_TOOL_DEFINITION = {
    "type": "function",
    "function": {
        "name": "export_to_word",
        "description": (
            "Export the answer and source references to a Word (.docx) document. "
            "Use this when the user asks to save, export, or download the answer as a Word file."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "Document title",
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "heading": {"type": "string"},
                            "content": {"type": "string"},
                        },
                    },
                    "description": "List of document sections with heading and content",
                },
            },
            "required": ["title", "sections"],
        },
    },
}

EXPORT_EXCEL_TOOL_DEFINITION = {
    "type": "function",
    "function": {
        "name": "export_to_excel",
        "description": (
            "Export tabular data to an Excel (.xlsx) file. "
            "Use this when the user asks to export data, tables, or structured information to Excel."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "sheet_name": {
                    "type": "string",
                    "description": "Name of the Excel sheet",
                },
                "headers": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Column header names",
                },
                "rows": {
                    "type": "array",
                    "items": {"type": "array"},
                    "description": "Data rows (each row is a list of values matching the headers)",
                },
            },
            "required": ["sheet_name", "headers", "rows"],
        },
    },
}


# ── Export Handlers ───────────────────────────────────────────────────────────

def export_to_word(
    title: str,
    sections: list[dict[str, str]],
    citations: list[dict] | None = None,
) -> bytes:
    """
    Generate a Word document from structured sections.

    Args:
        title: Document title
        sections: List of {"heading": str, "content": str} dicts
        citations: Optional citations to append as a references section

    Returns:
        .docx file as bytes
    """
    doc = DocxDocument()

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.runs[0].font.color.rgb = RGBColor(0x1A, 0x56, 0x76)

    # Metadata footer
    doc.add_paragraph(
        f"Generated by Sparkline AI | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    ).runs[0].font.size = Pt(9)

    doc.add_paragraph()

    # Sections
    for section in sections:
        if section.get("heading"):
            doc.add_heading(section["heading"], level=1)
        if section.get("content"):
            doc.add_paragraph(section["content"])

    # Citations
    if citations:
        doc.add_heading("Sources", level=1)
        for i, citation in enumerate(citations, start=1):
            page_str = f"p.{citation['page_number']}" if citation.get("page_number") else "N/A"
            doc.add_paragraph(
                f"{i}. {citation.get('document_name', 'Unknown')} | "
                f"Page: {page_str} | "
                f"Uploaded: {str(citation.get('version_uploaded_at', ''))[:10]}"
            )

    # Serialize to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()


def export_to_excel(
    sheet_name: str,
    headers: list[str],
    rows: list[list[Any]],
) -> bytes:
    """
    Generate an Excel workbook from headers + row data.

    Args:
        sheet_name: Worksheet name
        headers: Column names (first row)
        rows: Data rows

    Returns:
        .xlsx file as bytes
    """
    wb = Workbook()
    ws = wb.active
    ws.title = sheet_name

    # Header row with styling
    header_fill = PatternFill("solid", fgColor="1A5676")
    header_font = Font(bold=True, color="FFFFFF")

    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.fill = header_fill
        cell.font = header_font

    # Data rows
    for row_idx, row in enumerate(rows, start=2):
        for col_idx, value in enumerate(row, start=1):
            ws.cell(row=row_idx, column=col_idx, value=value)

    # Auto-fit column widths
    for col in ws.columns:
        max_length = max(len(str(cell.value or "")) for cell in col)
        ws.column_dimensions[col[0].column_letter].width = min(max_length + 4, 50)

    # Serialize to bytes
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer.read()
